# Generated by Django 5.2.8 on 2025-11-06 03:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=500, null=True)),
                ('image_url', models.URLField(max_length=500)),
                ('banner_type', models.CharField(choices=[('hero', 'Hero Banner'), ('promo', 'Promo Banner'), ('category', 'Category Banner')], db_index=True, default='hero', max_length=20)),
                ('button_text', models.CharField(blank=True, max_length=100, null=True)),
                ('link_url', models.URLField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('view_count', models.IntegerField(default=0)),
                ('click_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'db_table': 'banners',
                'ordering': ['sort_order', '-created_at'],
                'indexes': [models.Index(fields=['banner_type', 'is_active'], name='banners_banner__cfcffa_idx'), models.Index(fields=['sort_order'], name='banners_sort_or_a2a0ff_idx')],
            },
        ),
    ]
