# Generated by Django 5.2.8 on 2025-11-06 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='market',
            field=models.CharField(choices=[('KG', 'Kyrgyzstan'), ('US', 'United States'), ('ALL', 'All Markets')], db_index=True, default='ALL', max_length=3),
        ),
        migrations.AddIndex(
            model_name='banner',
            index=models.Index(fields=['market', 'banner_type', 'is_active'], name='banners_market_0d7c3a_idx'),
        ),
    ]
