# Generated by Django 5.2.8 on 2025-11-06 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='market',
            field=models.CharField(choices=[('KG', 'Kyrgyzstan'), ('US', 'United States')], db_index=True, default='KG', max_length=2),
        ),
        migrations.AddField(
            model_name='address',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='market',
            field=models.CharField(choices=[('KG', 'Kyrgyzstan'), ('US', 'United States')], db_index=True, default='KG', max_length=2),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='market',
            field=models.CharField(choices=[('KG', 'Kyrgyzstan'), ('US', 'United States')], db_index=True, default='KG', max_length=2),
        ),
        migrations.AddField(
            model_name='verificationcode',
            name='market',
            field=models.CharField(choices=[('KG', 'Kyrgyzstan'), ('US', 'United States')], db_index=True, default='KG', max_length=2),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='card_type',
            field=models.CharField(choices=[('visa', 'Visa'), ('mastercard', 'Mastercard'), ('mir', 'MIR'), ('amex', 'American Express'), ('other', 'Other')], default='visa', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='payment_type',
            field=models.CharField(choices=[('card', 'Credit/Debit Card'), ('cash', 'Cash on Delivery'), ('bank_transfer', 'Bank Transfer'), ('digital_wallet', 'Digital Wallet')], default='card', max_length=20),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['user', 'market'], name='addresses_user_id_460877_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['market', '-created_at'], name='notificatio_market_e78664_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentmethod',
            index=models.Index(fields=['user', 'market'], name='payment_met_user_id_c4657d_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationcode',
            index=models.Index(fields=['market', '-created_at'], name='verificatio_market_05b105_idx'),
        ),
    ]
