# Generated by Django 5.2.8 on 2025-11-08 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='card_type',
            field=models.CharField(choices=[('visa', 'Visa'), ('mastercard', 'Mastercard'), ('mir', 'MIR'), ('amex', 'American Express'), ('other', 'Unknown')], default='visa', max_length=20),
        ),
    ]
