# Generated by Django 5.2.8 on 2025-11-15 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userphonenumber'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='userphonenumber',
            new_name='user_phone__user_id_2d75bf_idx',
            old_name='user_phone__user_id_68db7c_idx',
        ),
        migrations.RenameIndex(
            model_name='userphonenumber',
            new_name='user_phone__user_id_706639_idx',
            old_name='user_phone__user_id_7363d9_idx',
        ),
        migrations.AlterField(
            model_name='userphonenumber',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
