# Generated by Django 5.2.8 on 2025-11-18 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_user_phone__user_id_68db7c_idx_user_phone__user_id_2d75bf_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='comment',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='entrance',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='floor',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
