# Generated by Django 5.2.8 on 2025-12-10 04:00

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0014_make_store_not_null'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Delivery fee amount', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_active', models.BooleanField(default=True, help_text='Is this fee configuration active?')),
                ('description', models.TextField(blank=True, help_text='Description of this delivery fee configuration', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='Category for this fee (required)', on_delete=django.db.models.deletion.CASCADE, related_name='delivery_fees', to='products.category')),
                ('second_subcategory', models.ForeignKey(blank=True, help_text='Second-level subcategory (optional, most specific fee)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_level_delivery_fees', to='products.subcategory')),
                ('subcategory', models.ForeignKey(blank=True, help_text='First-level subcategory (optional, for more specific fee)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_fees', to='products.subcategory')),
            ],
            options={
                'verbose_name': 'Delivery Fee',
                'verbose_name_plural': 'Delivery Fees',
                'db_table': 'delivery_fees',
                'ordering': ['category', 'subcategory', 'second_subcategory'],
                'indexes': [models.Index(fields=['category', 'subcategory', 'second_subcategory', 'is_active'], name='delivery_fe_categor_c46e1d_idx'), models.Index(fields=['category', 'is_active'], name='delivery_fe_categor_ec3f4f_idx')],
            },
        ),
    ]
