# Generated by Django 5.2.8 on 2025-11-06 04:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(choices=[('KG', 'Kyrgyzstan'), ('US', 'United States')], default='KG', max_length=2)),
                ('report_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generated', 'Generated'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('report_data', models.JSONField(default=dict)),
                ('sent_to_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Daily Report',
                'verbose_name_plural': 'Daily Reports',
                'db_table': 'daily_reports',
                'ordering': ['-report_date'],
            },
        ),
        migrations.CreateModel(
            name='ManagerSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('ky', 'Кыргызча'), ('en', 'English')], default='ru', max_length=2)),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'System')], default='light', max_length=10)),
                ('active_market', models.CharField(choices=[('KG', 'Kyrgyzstan'), ('US', 'United States')], default='KG', max_length=2)),
                ('notify_new_orders', models.BooleanField(default=True)),
                ('notify_status_changes', models.BooleanField(default=True)),
                ('notify_daily_report', models.BooleanField(default=True)),
                ('notify_delivery_errors', models.BooleanField(default=False)),
                ('report_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('default_order_filter', models.CharField(default='Все', max_length=20)),
                ('orders_per_page', models.IntegerField(default=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Manager Settings',
                'verbose_name_plural': 'Manager Settings',
                'db_table': 'manager_settings',
            },
        ),
        migrations.CreateModel(
            name='StoreManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('viewer', 'Viewer')], default='manager', max_length=20)),
                ('can_manage_kg', models.BooleanField(default=True)),
                ('can_manage_us', models.BooleanField(default=False)),
                ('can_view_orders', models.BooleanField(default=True)),
                ('can_edit_orders', models.BooleanField(default=True)),
                ('can_cancel_orders', models.BooleanField(default=True)),
                ('can_view_revenue', models.BooleanField(default=True)),
                ('can_export_data', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Store Manager',
                'verbose_name_plural': 'Store Managers',
                'db_table': 'store_managers',
            },
        ),
        migrations.CreateModel(
            name='ManagerActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('view_order', 'Viewed Order'), ('update_status', 'Updated Order Status'), ('cancel_order', 'Cancelled Order'), ('resume_order', 'Resumed Order'), ('export_data', 'Exported Data'), ('view_revenue', 'Viewed Revenue'), ('switch_market', 'Switched Market View'), ('login', 'Logged In'), ('logout', 'Logged Out')], db_index=True, max_length=20)),
                ('market', models.CharField(blank=True, choices=[('KG', 'Kyrgyzstan'), ('US', 'United States')], max_length=2, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('old_value', models.CharField(blank=True, max_length=255, null=True)),
                ('new_value', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_logs', to='orders.order')),
            ],
            options={
                'verbose_name': 'Manager Activity Log',
                'verbose_name_plural': 'Manager Activity Logs',
                'db_table': 'manager_activity_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ManagerNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('new_order', 'New Order'), ('status_change', 'Order Status Changed'), ('delivery_error', 'Delivery Error'), ('system', 'System Notification')], default='system', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('market', models.CharField(blank=True, choices=[('KG', 'Kyrgyzstan'), ('US', 'United States')], max_length=2, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('action_url', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
            options={
                'verbose_name': 'Manager Notification',
                'verbose_name_plural': 'Manager Notifications',
                'db_table': 'manager_notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RevenueSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(choices=[('KG', 'Kyrgyzstan'), ('US', 'United States')], db_index=True, default='KG', max_length=2)),
                ('snapshot_type', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=10)),
                ('snapshot_date', models.DateField(db_index=True)),
                ('snapshot_hour', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='сом', max_length=10)),
                ('currency_code', models.CharField(default='KGS', max_length=3)),
                ('total_orders', models.IntegerField(default=0)),
                ('completed_orders', models.IntegerField(default=0)),
                ('cancelled_orders', models.IntegerField(default=0)),
                ('pending_orders', models.IntegerField(default=0)),
                ('average_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('revenue_change_percent', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('orders_change_percent', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Revenue Snapshot',
                'verbose_name_plural': 'Revenue Snapshots',
                'db_table': 'revenue_snapshots',
                'ordering': ['-snapshot_date', '-snapshot_hour'],
                'indexes': [models.Index(fields=['market', 'snapshot_date'], name='revenue_sna_market_e67280_idx'), models.Index(fields=['snapshot_type', 'snapshot_date'], name='revenue_sna_snapsho_03cc96_idx')],
                'unique_together': {('market', 'snapshot_type', 'snapshot_date', 'snapshot_hour')},
            },
        ),
    ]
