# Generated by Django 5.2.8 on 2025-11-06 04:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store_manager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='storemanager',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manager_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='managersettings',
            name='manager',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='store_manager.storemanager'),
        ),
        migrations.AddField(
            model_name='managernotification',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='store_manager.storemanager'),
        ),
        migrations.AddField(
            model_name='manageractivitylog',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='store_manager.storemanager'),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='store_manager.storemanager'),
        ),
        migrations.AddIndex(
            model_name='managernotification',
            index=models.Index(fields=['manager', 'is_read', '-created_at'], name='manager_not_manager_769032_idx'),
        ),
        migrations.AddIndex(
            model_name='manageractivitylog',
            index=models.Index(fields=['manager', '-created_at'], name='manager_act_manager_0dd6dc_idx'),
        ),
        migrations.AddIndex(
            model_name='manageractivitylog',
            index=models.Index(fields=['action_type', '-created_at'], name='manager_act_action__26fde4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyreport',
            unique_together={('manager', 'market', 'report_date')},
        ),
    ]
