# Generated by Django 5.2.8 on 2025-11-06 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='market',
            field=models.CharField(choices=[('KG', 'Kyrgyzstan'), ('US', 'United States')], default='KG', max_length=2),
        ),
        migrations.AlterField(
            model_name='manageractivitylog',
            name='action_type',
            field=models.CharField(choices=[('view_order', 'Viewed Order'), ('update_status', 'Updated Order Status'), ('cancel_order', 'Cancelled Order'), ('resume_order', 'Resumed Order'), ('export_data', 'Exported Data'), ('view_revenue', 'Viewed Revenue'), ('switch_market', 'Switched Market View'), ('login', 'Logged In'), ('logout', 'Logged Out')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='manageractivitylog',
            name='market',
            field=models.CharField(blank=True, choices=[('KG', 'Kyrgyzstan'), ('US', 'United States')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='managernotification',
            name='market',
            field=models.CharField(blank=True, choices=[('KG', 'Kyrgyzstan'), ('US', 'United States')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='managersettings',
            name='active_market',
            field=models.CharField(choices=[('KG', 'Kyrgyzstan'), ('US', 'United States')], default='KG', max_length=2),
        ),
        migrations.AlterField(
            model_name='revenuesnapshot',
            name='market',
            field=models.CharField(choices=[('KG', 'Kyrgyzstan'), ('US', 'United States')], db_index=True, default='KG', max_length=2),
        ),
    ]
