# Generated by Django 5.2.8 on 2025-12-10 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_manager', '0002_initial'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storemanager',
            name='store',
            field=models.ForeignKey(blank=True, help_text='Store this manager manages (null for platform-wide managers)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managers', to='stores.store'),
        ),
    ]
