# Generated by Django 5.2.8 on 2025-12-10 01:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('market', models.CharField(choices=[('KG', 'Kyrgyzstan'), ('US', 'United States'), ('ALL', 'All Markets')], db_index=True, default='KG', help_text='Primary market for this store', max_length=3)),
                ('logo', models.ImageField(blank=True, help_text='Store logo image', null=True, upload_to='stores/logos/')),
                ('logo_url', models.URLField(blank=True, help_text='Alternative: External logo URL', max_length=500, null=True)),
                ('cover_image', models.ImageField(blank=True, help_text='Store cover/banner image', null=True, upload_to='stores/covers/')),
                ('cover_image_url', models.URLField(blank=True, help_text='Alternative: External cover image URL', max_length=500, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('website', models.URLField(blank=True, max_length=500, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, help_text='Average rating from reviews', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('reviews_count', models.IntegerField(default=0, help_text='Total number of reviews')),
                ('orders_count', models.IntegerField(default=0, help_text='Total number of orders')),
                ('products_count', models.IntegerField(default=0, help_text='Total number of active products')),
                ('likes_count', models.IntegerField(default=0, help_text='Total number of likes/followers')),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('active', 'Active'), ('suspended', 'Suspended'), ('closed', 'Closed')], db_index=True, default='pending', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Verified store badge (admin approved)')),
                ('is_featured', models.BooleanField(default=False, help_text='Featured store (shown prominently)')),
                ('contract_signed_date', models.DateTimeField(blank=True, null=True)),
                ('contract_expiry_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(help_text='Business owner who manages this store', on_delete=django.db.models.deletion.CASCADE, related_name='owned_stores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Store',
                'verbose_name_plural': 'Stores',
                'db_table': 'stores',
                'ordering': ['-is_featured', '-rating', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoreFollower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='stores.store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_stores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Store Follower',
                'verbose_name_plural': 'Store Followers',
                'db_table': 'store_followers',
            },
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['slug'], name='stores_slug_27d58c_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['market', 'is_active', 'status'], name='stores_market_6650ce_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['owner', 'is_active'], name='stores_owner_i_221d3b_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['is_featured', '-rating'], name='stores_is_feat_0e9924_idx'),
        ),
        migrations.AddIndex(
            model_name='storefollower',
            index=models.Index(fields=['user', '-created_at'], name='store_follo_user_id_56f8a3_idx'),
        ),
        migrations.AddIndex(
            model_name='storefollower',
            index=models.Index(fields=['store', '-created_at'], name='store_follo_store_i_cabc30_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='storefollower',
            unique_together={('user', 'store')},
        ),
    ]
