# Generated by Django 5.2.8 on 2025-11-06 03:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='market',
            field=models.CharField(choices=[('KG', 'Kyrgyzstan'), ('US', 'United States')], db_index=True, default='KG', max_length=2),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['market', 'status'], name='orders_market_2e5134_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['market', '-created_at'], name='orders_market_03c0eb_idx'),
        ),
    ]
