# Generated by Django 5.2.8 on 2025-11-16 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='requested_delivery_date',
            field=models.DateField(blank=True, help_text='Date when customer wants the order delivered', null=True),
        ),
    ]
