# Generated by Django 5.2.8

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_requested_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='orders/reviews/'),
        ),
        migrations.AlterField(
            model_name='reviewimage',
            name='image_url',
            field=models.URLField(blank=True, help_text='Optional: External image URL (if not uploading a file)', max_length=500, null=True),
        ),
    ]

