# Generated by Django 5.2.8 on 2025-11-06 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_market_order_orders_market_2e5134_idx_and_more'),
        ('users', '0002_address_market_address_state_notification_market_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='card_last_four',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='card_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_country',
            field=models.CharField(default='Kyrgyzstan', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method_used',
            field=models.ForeignKey(blank=True, help_text='Reference to the payment method used (preserved for history)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_paid_with', to='users.paymentmethod'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(blank=True, help_text='Reference to the address used (preserved for history even if address is deleted)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_shipped_to', to='users.address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Credit/Debit Card'), ('cash', 'Cash on Delivery'), ('transfer', 'Bank Transfer'), ('digital_wallet', 'Digital Wallet')], default='cash', max_length=20),
        ),
    ]
