# Generated by Django 5.2.8 on 2025-12-10 03:53

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_fix_review_rating_validation'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='referral_fee_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total referral fee amount for this item (calculated)', max_digits=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='referral_fee_fixed',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Fixed referral fee amount for this item', max_digits=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='referral_fee_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Referral fee percentage applied to this item', max_digits=5),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='store_revenue',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Net revenue for store after referral fee (subtotal - referral_fee_amount)', max_digits=10),
        ),
    ]
