# Generated by Django 5.2.8 on 2025-12-10 04:01

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orderitem_referral_fee_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='delivery_fee_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Delivery fee amount for this item (based on product category)', max_digits=10),
        ),
    ]
