# Generated by Django 5.2.8 on 2025-12-10 08:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_orderitem_delivery_fee_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='store_revenue',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Net revenue for store after referral fee (subtotal - referral_fee_amount). Note: Delivery fees are kept by platform, not deducted from store revenue.', max_digits=10),
        ),
    ]
