# Generated by Django 5.2.8 on 2025-11-06 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='market',
            field=models.CharField(choices=[('KG', 'Kyrgyzstan'), ('US', 'United States'), ('ALL', 'All Markets')], db_index=True, default='ALL', max_length=3),
        ),
        migrations.AddField(
            model_name='product',
            name='market',
            field=models.CharField(choices=[('KG', 'Kyrgyzstan'), ('US', 'United States'), ('ALL', 'All Markets')], db_index=True, default='KG', max_length=3),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=120),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('name', 'market')},
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['market', 'is_active'], name='categories_market_f37210_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['market', 'is_active', 'in_stock'], name='products_market_0274d8_idx'),
        ),
    ]
