# Generated by Django 5.2.8 on 2025-11-06 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_market_product_market_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='activity_tags',
            field=models.JSONField(blank=True, default=list, help_text="Activities: ['dancing', 'socializing', 'partying']"),
        ),
        migrations.AddField(
            model_name='product',
            name='age_group_tags',
            field=models.JSONField(blank=True, default=list, help_text="Age groups: ['young_adults', 'adults']"),
        ),
        migrations.AddField(
            model_name='product',
            name='ai_description',
            field=models.TextField(blank=True, help_text='Detailed description for AI to understand product better', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='color_tags',
            field=models.JSONField(blank=True, default=list, help_text="Colors: ['black', 'blue', 'white']"),
        ),
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('M', 'Men'), ('W', 'Women'), ('U', 'Unisex'), ('K', 'Kids')], default='U', help_text='Target gender', max_length=1),
        ),
        migrations.AddField(
            model_name='product',
            name='material_tags',
            field=models.JSONField(blank=True, default=list, help_text="Materials: ['cotton', 'polyester', 'breathable']"),
        ),
        migrations.AddField(
            model_name='product',
            name='occasion_tags',
            field=models.JSONField(blank=True, default=list, help_text="Suitable occasions: ['party', 'night_out', 'clubbing']"),
        ),
        migrations.AddField(
            model_name='product',
            name='season_tags',
            field=models.JSONField(blank=True, default=list, help_text="Suitable seasons: ['summer', 'spring', 'all-season']"),
        ),
        migrations.AddField(
            model_name='product',
            name='style_tags',
            field=models.JSONField(blank=True, default=list, help_text="Style attributes: ['casual', 'trendy', 'modern']"),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['gender', 'market'], name='products_gender_506354_idx'),
        ),
    ]
