# Generated by Django 5.2.8 on 2025-11-15 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_sku_size_color_refactor'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/subcategories/'),
        ),
        migrations.AlterField(
            model_name='productcoloroption',
            name='hex_code',
            field=models.CharField(help_text='HEX code (#FFFFFF).', max_length=7, null=True),
        ),
    ]
