# Generated by Django 5.2.8 on 2025-11-23 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_subcategory_image_alter_productcoloroption_hex_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='ISO 4217 currency code (e.g., USD, KGS, EUR)', max_length=3, unique=True)),
                ('name', models.CharField(help_text='Currency name (e.g., US Dollar, Kyrgyzstani Som)', max_length=100)),
                ('symbol', models.CharField(help_text='Currency symbol (e.g., $, сом, €)', max_length=10)),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=1.0, help_text='Exchange rate relative to base currency (USD). 1 USD = exchange_rate of this currency', max_digits=12)),
                ('is_base', models.BooleanField(default=False, help_text='Is this the base currency?')),
                ('is_active', models.BooleanField(default=True)),
                ('market', models.CharField(choices=[('KG', 'Kyrgyzstan'), ('US', 'United States'), ('ALL', 'All Markets')], default='ALL', help_text='Primary market for this currency', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
                'db_table': 'currencies',
                'ordering': ['code'],
                'indexes': [models.Index(fields=['code', 'is_active'], name='currencies_code_f4c797_idx'), models.Index(fields=['market', 'is_active'], name='currencies_market_985824_idx')],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.ForeignKey(blank=True, help_text="Currency for this product's price. If not set, uses market default.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.currency'),
        ),
        migrations.AddField(
            model_name='sku',
            name='currency',
            field=models.ForeignKey(blank=True, help_text="Currency for this SKU's price. If not set, uses product currency.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='skus', to='products.currency'),
        ),
    ]
