# Generated by Django 5.2.8 on 2025-12-03 01:00

import django.db.models.deletion
import django.utils.text
from django.db import migrations, models


def migrate_brand_data_forward(apps, schema_editor):
    """
    Data migration: Extract unique brands from Product.brand CharField
    and create Brand instances, then link products to them.
    """
    Product = apps.get_model('products', 'Product')
    Brand = apps.get_model('products', 'Brand')
    db_alias = schema_editor.connection.alias
    
    # Get table names from model Meta - should be 'products' and 'brands'
    product_table = Product._meta.db_table
    brand_table = Brand._meta.db_table
    
    # Use raw SQL to get unique brand names from the old CharField
    # At this point in the migration, the 'products' table exists with 'brand' CharField
    # Quote table name properly using schema editor
    quoted_product_table = schema_editor.quote_name(product_table)
    
    with schema_editor.connection.cursor() as cursor:
        # Use raw SQL with properly quoted table name
        cursor.execute(
            f'SELECT DISTINCT brand FROM {quoted_product_table} WHERE brand IS NOT NULL AND brand != \'\''
        )
        rows = cursor.fetchall()
        unique_brand_names = {row[0].strip() for row in rows if row[0] and row[0].strip()}
    
    if not unique_brand_names:
        print("⚠️ No brands found to migrate")
        return
    
    # Create Brand instances
    brand_mapping = {}
    for brand_name in unique_brand_names:
        if brand_name:
            slug = django.utils.text.slugify(brand_name)
            # Handle slug uniqueness
            original_slug = slug
            counter = 1
            while Brand.objects.using(db_alias).filter(slug=slug).exists():
                slug = f"{original_slug}-{counter}"
                counter += 1
            
            brand, created = Brand.objects.using(db_alias).get_or_create(
                slug=slug,
                defaults={
                    'name': brand_name,
                    'is_active': True,
                }
            )
            brand_mapping[brand_name] = brand
            if created:
                print(f"  Created brand: {brand_name} (slug: {slug})")
    
    # Update products to use Brand ForeignKey via raw SQL
    quoted_product_table = schema_editor.quote_name(product_table)
    updated_count = 0
    for brand_name, brand_obj in brand_mapping.items():
        with schema_editor.connection.cursor() as cursor:
            cursor.execute(
                f'UPDATE {quoted_product_table} SET brand_fk_id = %s WHERE brand = %s',
                [brand_obj.id, brand_name]
            )
            updated_count += cursor.rowcount
    
    print(f"✅ Migrated {len(brand_mapping)} brands and updated {updated_count} products")


def migrate_brand_data_reverse(apps, schema_editor):
    """Reverse migration: Convert Brand ForeignKey back to CharField"""
    Product = apps.get_model('products', 'Product')
    Brand = apps.get_model('products', 'Brand')
    db_alias = schema_editor.connection.alias
    
    product_table = Product._meta.db_table
    brand_table = Brand._meta.db_table
    
    # Quote table names properly
    quoted_product_table = schema_editor.quote_name(product_table)
    quoted_brand_table = schema_editor.quote_name(brand_table)
    
    # Update products to use brand name from ForeignKey via raw SQL
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            f'SELECT p.id, b.name FROM {quoted_product_table} p JOIN {quoted_brand_table} b ON p.brand_fk_id = b.id WHERE p.brand_fk_id IS NOT NULL'
        )
        rows = cursor.fetchall()
        
        for product_id, brand_name in rows:
            cursor.execute(
                f'UPDATE {quoted_product_table} SET brand = %s WHERE id = %s',
                [brand_name, product_id]
            )


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_currency_product_currency_sku_currency'),
    ]

    operations = [
        # Step 1: Create Brand model
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='brands/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
                'db_table': 'brands',
                'ordering': ['name'],
                'indexes': [
                    models.Index(fields=['slug'], name='brands_slug_6a4b1c_idx'),
                    models.Index(fields=['is_active'], name='brands_is_acti_101dba_idx')
                ],
            },
        ),
        
        # Step 2: Add new ForeignKey field (nullable, with temporary name)
        migrations.AddField(
            model_name='product',
            name='brand_fk',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='products_temp',
                to='products.brand',
            ),
        ),
        
        # Step 3: Migrate data from CharField to ForeignKey
        migrations.RunPython(migrate_brand_data_forward, migrate_brand_data_reverse),
        
        # Step 4: Remove old CharField
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        
        # Step 5: Rename brand_fk to brand
        migrations.RenameField(
            model_name='product',
            old_name='brand_fk',
            new_name='brand',
        ),
        
        # Step 6: Update the related_name to the correct one
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(
                blank=True,
                help_text='Product brand',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='products',
                to='products.brand'
            ),
        ),
    ]
