# Generated by Django 5.2.8 on 2025-12-03 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_brand_alter_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='Category image/icon', null=True, upload_to='categories/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image_url',
            field=models.URLField(blank=True, help_text='Alternative: External image URL (if not uploading file)', max_length=500, null=True),
        ),
    ]
