# Generated by Django 5.2.8 on 2025-12-03 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_add_category_image_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, help_text='Category icon file (small icon image)', null=True, upload_to='categories/icons/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='Category image', null=True, upload_to='categories/'),
        ),
    ]
