# Generated by Django 5.2.8 on 2025-12-03 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_add_category_icon_imagefield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, help_text='Category icon file (upload icon image)', null=True, upload_to='categories/icons/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='Category image/icon', null=True, upload_to='categories/'),
        ),
    ]
