# Generated by Django 5.2.8 on 2025-12-10 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_add_flexible_catalog_structure'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='products_categor_c7ae61_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='products_categor_ac40f9_idx',
            old_name='products_categor_idx',
        ),
        migrations.RenameIndex(
            model_name='subcategory',
            new_name='subcategori_categor_f51d65_idx',
            old_name='subcategori_categor_idx',
        ),
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.ForeignKey(blank=True, help_text='Store that sells this product (for marketplace)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='stores.store'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(blank=True, help_text='First-level subcategory. Required for level 2 and 3 catalog.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.subcategory'),
        ),
        migrations.AlterField(
            model_name='productcoloroption',
            name='hex_code',
            field=models.CharField(blank=True, help_text='HEX code (#FFFFFF).', max_length=7, null=True),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['store', 'is_active'], name='products_store_i_7e53ff_idx'),
        ),
    ]
