# Generated by Django 5.2.8

from django.db import migrations


def assign_products_to_default_store(apps, schema_editor):
    """Assign all products without a store to a default store."""
    Product = apps.get_model('products', 'Product')
    Store = apps.get_model('stores', 'Store')
    User = apps.get_model('users', 'User')
    
    # Get or create a default store
    # First, try to find an existing store
    default_store = Store.objects.first()
    
    if not default_store:
        # Create a default store if none exists
        # Get or create a default admin user
        admin_user = User.objects.filter(is_staff=True).first()
        if not admin_user:
            admin_user = User.objects.first()
        
        if admin_user:
            default_store = Store.objects.create(
                name='Default Store',
                owner=admin_user,
                market='KG',
                status='active',
                is_active=True,
                description='Default store for products without a store',
            )
    
    if default_store:
        # Assign all products without a store to the default store
        Product.objects.filter(store__isnull=True).update(store=default_store)


def reverse_assign_products(apps, schema_editor):
    """Reverse migration - set store to None (but this won't work after making it required)"""
    # This is a one-way migration
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_remove_product_products_categor_c7ae61_idx_and_more'),
        ('stores', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(assign_products_to_default_store, reverse_assign_products),
    ]
