# Generated by Django 5.2.8

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_make_store_required'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='store',
            field=models.ForeignKey(
                help_text='Store that sells this product (required for marketplace)',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='products',
                to='stores.store'
            ),
        ),
    ]

